obj-$(CONFIG_POWER_AVS)		+= avs/
obj-$(CONFIG_POWER_RESET)	+= reset/
obj-$(CONFIG_POWER_SUPPLY)	+= supply/
obj-$(CONFIG_QNS_SYSTEM)	+= qns_system.o
obj-$(CONFIG_WIRELESS_CHARGER_P9221)	+= p9221_wl_charger.o
